### ISSUE TITLE
Verticall scrolling doesnot work while in a container with horizontal scrolling is encountered

### ISSUE THREAD

**Issue by shankarregmi** [asvd/dragscroll#14]
I have two containers : one is parent which scrolls vertically and inside parent there is another horizontal scrolling div. when I reach child container with horizontal scrolling vertical scrolling does not work.

**Comment by asvd** [comment]
1. Do you have an online demo?

2. Which container do you want to be scrolled when you drag the child container?

**Comment by shankarregmi** [comment]
I have a big parent container which scrolls vertically, it works fine. But in the middle of the div there is another child container which scrolls horizontally. When I reach that child container and try to scroll up the parent container I cannot . I just want to bubble up the mouseup event on the child container towards parent container. How can I achieve this? please help

**Comment by asvd** [comment]
If you set the `dragscroll` attribute for the parent container, and not for the child container, it should work as described (until there is a bug in dragscroll). Do you have a simple online demo where this can be reproduced?

**Comment by shankarregmi** [comment]
yeah, fixed above issue, with propagating  event on mouse move

**Comment by asvd** [comment]
I'm wondering if it's not propagated by default

**Comment by shankarregmi** [comment]
yeah, just commented out a single line and its working like a charm

**Comment by asvd** [comment]
which line?

**Comment by shankarregmi** [comment]
line no 48 `e.stopPropagation()`
![screenshot from 2016-02-19 23 05 34](https://cloud.githubusercontent.com/assets/7703345/13183102/51e971aa-d75d-11e5-9853-5cf87360353d.png)

**Comment by asvd** [comment]
eventually this issue has already been fixed some commits ago and released in v0.0.6
