### ISSUE TITLE
Reinit method

### ISSUE THREAD

**Issue by epszaw** [asvd/dragscroll#26]
Hello!
I try to use `dragscroll` with react-based application.
I have multiple routes and when dragscroll-allowed route was mounted (directly visited), dragscroll work perfectly.
But, when other route mouted before dragscroll-allowed route - dragscroll not worked.
What I do wrong or how I can reinit `dragscroll`?

**Comment by asvd** [comment]
try `dragscroll.reset()`

**Comment by epszaw** [comment]
My fault.
I call `reset()` in `componentWillMount`, but must do it in `componentDidMount`.
Thank you! :smile_cat:
