### ISSUE TITLE
Dynamically removing dragscroll from an element

### ISSUE THREAD

**Issue by zekial** [asvd/dragscroll#4]
Great library, thanks.  I'm trying to dynamically enable/disable dragscroll for an element.  Enabling it works fine - I add the 'dragscroll' class and then call dragscroll.reset().  However, removing the class and again calling dragscroll.reset() does not remove the event listeners - the element is still draggable.  Any suggestions on how to do this?

**Comment by xcy7e** [comment]
Having the same issue.

**Comment by inovek** [comment]
I added a simple condition to check if my own variable "draggable" is true. If not, dragscroll don't scroll anything. (https://github.com/inovek/dragscroll/blob/885180334b276094d81b761446fc679945d61057/dragscroll.js)

**Comment by mosta2** [comment]
Any solution for this problem?

**Comment by asvd** [comment]
Reproduced, will prepare a solution shortly

**Comment by asvd** [comment]
Released in [v0.0.6](https://github.com/asvd/dragscroll/releases/tag/v0.0.6)
