### ISSUE TITLE
Scrolling an element with the entire page

### ISSUE THREAD

**Issue by simionas** [asvd/dragscroll#5]
This is very useful. Works great. But I'm trying to do something and it ends up with an element over the element I want to be scrolled, and the element over it is disabling scrolling for the one under. 

Can anyone help me to make it so when I drag on the entire HTML page, a specific element to be scrolled?

**Comment by asvd** [comment]
Try to apply css-rule pointerEvents:none to the topmost element, then it should become transparent to mouse events.

**Comment by simionas** [comment]
I will do that. Thank you very much!
